class ObjectOriginals:
    def __init__(self):
        self.sectionComingSoon = "//div[contains(text(), 'Coming Soon')]"
        self.slideRightCluster = "//*[@id='strip-element-2']/div[2]/div/div[2]/md-icon"
        self.slideLeftCluster = "//*[@id='strip-element-2']/div[2]/div/div[1]/md-icon"
        self.cardCinlock = "//div[@id='scroll-surface-2']/div[1]/node-poster/div/div[3]/span/div[2]"
        self.clickBanner = "//div[@id='play-button-0']"
        self.slideBannerRight = "//*[@id='banner-strip-0']/div[2]/md-icon"
        self.slideBannerLeft = "//*[@id='banner-strip-0']/div[1]/md-icon"
        self.sypnosis = "//*[@id='synopsis']"
        self.btnSubscribe = "//span[contains(text(), 'Subscribe')]"
        self.btnWatch = "//button[@aria-label='Watch']"
        self.btnWatch2 = "//span[contains(text(), 'Watch')]"
        self.btnConnectDevice = "//md-dialog-actions/button[2]/span"
        self.timeAds = "//div[@class='videoAdUiAttribution']"
        self.iFrameAds = "//iframe[@title='Advertisement']"
        self.btnSkipAds = "//div[@class='videoAdUiSkipButtonExperimentalText']"
        self.videoPlayer = "//*[@id='player'']/div/div[1]/div[2]/div"
        self.idVideo = "//div[@id='player']"
        self.cardEpsThree = "//extended-info/div/div/div[2]/div[2]/content-seasons-episodes/div/div/div[2]/div/md-grid-list/md-grid-tile[3]/figure/content-small/cell-small/div/div[3]/div[2]/div/div"
        self.cardEpsTwo = "//extended-info/div/div/div[2]/div[2]/content-seasons-episodes/div/div/div[2]/div/md-grid-list/md-grid-tile[2]/figure/content-small/cell-small/div/div[3]/div[2]/div/div"
        self.popUpSubscribe = "//div[contains(text(), 'What do you want to subscribe to?')]"   
        self.btnTrailer = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[4]/div"
        self.btnAddToList = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[1]/div[1]/span"
        self.btnAddToListTrue = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[1]/div[1]/md-icon[@class='md-font material-icons icon-icon_wishlist_saved']"
        self.btnLike = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[2]/div/md-icon"
        self.btnLikeTrue = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[2]/div/md-icon[@class='md-font material-icons icon-like-fill']"
        self.btnPauseVideo = "//button[@class = 'md-icon-button pause md-button md-ink-ripple']"
        self.btnUnLike = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[3]/div[1]/md-icon"
        self.btnUnLikeTrue = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[3]/div[1]/md-icon[@class='md-font material-icons icon-dislike-fill']"
        self.btnShare = "//extended-info/div/div/div[2]/div[1]/div[1]/div[5]/div/div[2]/content-buttons/div/div[2]/button[5]/div[1]/md-icon"
        self.btnFacebook = "//md-list/md-list-item[1]/div[1]/button/div[1]"
        self.premium30DaysFromPopUpSubscribe = "//div/div[3]/div[1]/div[2]/div[1]"
        self.btnPricePackage = "//operator-info/div/div/div[2]/div/div/div[3]/span/button"
        self.iconSearch = "//md-toolbar/div/button[1]"
        self.inputSearch = "//input[@placeholder='Search']"
        self.cardResultSearch = "//div[2]/div/md-grid-list/md-grid-tile/figure/node-snapshot/div"
        self.timeVod = "//*[@id='player']/div/div[2]/player-progress-bar/div/div[3]/span"
        self.btnPause = "//button[@class='md-icon-button pause md-button md-ink-ripple']"
        self.MaximumDeviceTxt = "//div[contains(text(),'Maximum of devices')]"
        self.btnGoToSettingsMaximumDevice = "//span[contains(text(),'Go to settings')]"
        self.player = "//div[@id='player']"
        self.hoverContinue = "#scroll-surface-5 > div:nth-child(1) > node-snapshot > div"
        self.btnDownload = "//button[@aria-label='Download']"
        self.btnCancelDownload = "//button[@aria-label='Cancel download']"
        self.loveStoriesText = "//div[contains(text(), ' Love Stories ')]"
        self.cardLoveStories = "//*[@id='scroll-surface-3']/div[1]/node-poster/div"
        self.titleCardLoveStories = "//*[@id='scroll-surface-3']/div[1]/node-poster/div/div[3]/div/div/div"
        self.buttonSkipAds = "//button[@class='videoAdUiSkipButton videoAdUiAction videoAdUiRedesignedSkipButton']"
        self.frameAds = "(//iframe[@title='Advertisement'])[1]"
        self.titleCardOriginals = "//*[@id='scroll-surface-1']/div[3]/node-poster/div/div[3]/div/div/div"
        self.cardOriginals = "//*[@id='scroll-surface-1']/div[3]/node-poster/div/div[3]"
        self.navOriginals = "//a[text() = 'Original']"
        self.cardOriginalsFirst = "((//div[@class= 'swiper-slide overflow-hidden rounded-lg swiper-slide-active'])[1]//a//img)[2]"
        # self.cardOriginalsFirst = "(//img[@ src='https://www.visionplus.id/webclient/img/play_hover.svg'])[1]"
        self.buttonWatch = "//a[./div[text()='WATCH']]"
        self.buttonPause = "(//button[@class='btn btn-ghost'])[1]"
        self.cardIntoView = "(//div[@class='swiper-slide overflow-hidden rounded-lg swiper-slide-active'])[1]"
        self.clickEpisode3 = "//a[.//p[text()='Episode 3']]"
        self.tvIsPlaying = "(//button[@class='btn btn-ghost'])[1]"
        self.textUpgrade = "//div[text() = 'Upgrade']"