class objectBuyPackage:
    def __init__(self):
        self.navBuyPackage = "//li[@name='Buy Package']/button/span/span"
        self.txtPremium30Days = "(//div[contains(.,'Rp 20.000,00') and contains(.,'Premium 30 Days')])[10]"
        self.btnPricePremium30Days = "//span[contains(text(),'Rp 20.000,00')]"
        self.txtPaymentPremium30Days = "(//div[contains(.,'20.000') and contains(.,'Premium 30 Days')])[9]"
        self.txtPremiumSport30Days = "(//div[contains(.,'Rp 40.000,00') and contains(.,'Premium Sports 30 Days')])[10]"
        self.btnPricePremiumSport30Days = "//span[contains(text(),'Rp 40.000,00')]"
        self.txtPaymentPremiumSport30Days = "(//div[contains(.,'40.000') and contains(.,'Premium + Sports 30 Days')])[9]"
        self.btnPrice = "//div[@class='priceButton']/span/button"
        self.btnSubscribe = "//md-dialog/md-dialog-actions/button/span"
        self.choosePayment = "//img[@alt='logo QRIS']"
        self.chooseVA = "//span[contains(text(),'Virtual account')]"
        self.iframeChoosePayment = "//iframe[@id='snap-midtrans']"
        self.chooseVABCA = "//a[@href='#/bank-transfer/bca-va']"
        self.txtVA = "//div[@id='vaField']"
        self.btnBackToMerchant = "//button[contains(text(),'Back to merchant')]"
        self.chooseGopay = "//div[contains(text(),'GoPay/GoPay Later')]"
        self.imgQrCode = "//img[@class='qr-image']"
        self.txtShopeePay = "//div[contains(text(),'ShopeePay/SPayLater')]"
        self.chooseVAMandiri = "//a[@href='#/bank-transfer/mandiri-va']"
        self.chooseVAPermata = "//a[@href='#/bank-transfer/permata-va']"
        self.chooseVABNI = "//a[@href='#/bank-transfer/bni-va']"
        self.chooseVABRI = "//a[@href='#/bank-transfer/bri-va']"
        self.chooseVAOther = "//a[@href='#/bank-transfer/other-va']"
        self.chooseQris = "//div[contains(text(),'QRIS')]"
        self.chooseDebitOrKredit = "//div[contains(text(),'Credit/debit card')]"
        self.inputCvv = "//input[@id='card-cvv']"
        self.chooseTelcoBalance = "//p[contains(text(),'Telco Balance')]"
        self.chooseOtherPayment = "//p[contains(text(),'Other Payment')]"
        self.inputPhoneNumber =  "//input[@placeholder='Phone number (ex:083123xxx)']"
        self.btnContinuee = "//button[contains(text(),'Continue')]"
        self.NicePayPage = "//span[@id='transactionAmount']"
        self.txtProvide = "//label[@for='provider']"
        self.aTermAndCondition = "//a[contains(text(),'Terms of use')]"
        self.aPrivacyPolicy = "//a[contains(text(),'Privacy Policy')]"
        self.aSoftwareLicence = "//a[contains(text(),'Software Licenses')]"
        self.termAndConditionPage = "//div[@class='head font-semibold text-[18px] text-white']/p[contains(text(),'terms-and-conditons')]"
        self.privacyPolicyPage = "//div[@class='head font-semibold text-[18px] text-white']/p[contains(text(),'privacy')]"
        self.softwareLicencePage = "//div[@class='head font-semibold text-[18px] text-white']/p[contains(text(),'software-licenses')]"
        self.cardSubscribePackageActive = "//div[contains(text(),'days left')]"
        self.cardPackageEuro = "(//div[contains(.,'Rp 99.000,00') and contains(.,'EURO2024')])[10]"
        self.btnPriceEuro = "//span[contains(text(),'Rp 99.000,00')]"
        self.txtPaymentEuro = "(//div[contains(.,'99.000') and contains(.,'Euro Regular Pack')])[9]"
