class objectHomepage:
    def __init__(self):
        self.navHome = "//span[contains(text(), 'Home')]"
        self.cardRCTI = "//*[@id='scroll-surface-7']/div[2]/node-snapshot/div/div[3]"
        self.liveTvSection = "//div[contains(text(), ' Your Favorite TV Channel ')]"
        self.RCTISelectedLiveTv = "//div[@class='cell-channel selected' and @id='channel-00000000000000000002']"
        self.slideRightLiveTvFavorite = "//*[@id='strip-element-7']/div[2]/div/div[2]/md-icon"
        self.slideLeftLiveTvFavorite = "//*[@id='strip-element-7']/div[2]/div/div[1]/md-icon"
        self.CardTopTenWeekSection = "//*[@id='scroll-surface-16']/div[2]/node-shape/div/div/sdp-image/img"
        self.topTenSection = "//div[contains(text(), ' Top 10 This Week ')]"
        self.iconSearch = "//md-toolbar/div/button[1]"
        self.inputSearch = "//input[@placeholder='Search']"
        self.cardResultSearch = "//div[2]/div/md-grid-list/md-grid-tile/figure/node-snapshot/div"
        self.cardWatchlistVod = "//*[@id='scroll-surface-4']/div/node-poster/div"
        self.cardTitle = "//*[@id='scroll-surface-4']/div/node-poster/div/div/div"
        self.cardOriginal = "//*[@id='scroll-surface-2']/div[1]/node-poster/div/div[2]/div"
        self.RightSlideWatchlist = "(//div[@class='next'])[4]"
        self.LeftSlideWatchlist = "(//div[@class='prev'])[3]"
        self.watchlistSection = "//div[contains(text(), ' Watchlist ')]"
        self.slideLeftNewReleases = "//*[@id='strip-element-13']/div[2]/div/div[1]/md-icon"
        self.slideRightNewReleases = "//*[@id='strip-element-13']/div[2]/div/div[2]/md-icon"
        self.cardNewReleases = "//*[@id='scroll-surface-14']/div/node-poster/div"
        self.cardTitleNewReleases = "//*[@id='scroll-surface-14']/div[1]/node-poster/div/div[3]/div/div/div"
        self.newReleasesSection = "//div[contains(text(), ' New Releases ')]"
        self.slideLeftContinueWatching = "//*[@id='strip-element-5']/div[2]/div/div[1]/md-icon"
        self.slideRightContinueWatching = "//*[@id='strip-element-5']/div[2]/div/div[2]/md-icon"
        self.cardContinueWatching = "//*[@id='scroll-surface-5']/div[1]/node-snapshot/div/div[3]"
        self.continueWatchingSection = "//div[contains(text(), ' Continue watching ')]"
        self.iconPlayContinueWatching = "//*[@id='scroll-surface-5']/div[3]/node-snapshot/div/div[3]"
        self.hoverContinueWatching = "#scroll-surface-5 > div:nth-child(1) > node-snapshot > div"
        self.titleContinue = "#scroll-surface-5 > div:nth-child(1) > node-snapshot > div > div.cell-info > div.description.layout-align-space-around-start.layout-column > div > div"
        self.layoutWatching = "(//div[@class='rendering-space layout-align-center-center layout-row'])[3]"
        self.iconProfileAvatar = "//img[@data-cy='avatar-header-img']"

        