class objectLogin:
    def __init__(self):
        self.buttonLogin = "//button[text() = 'LOG IN']"
        self.buttonLoginRegis = "//span[contains(text(), 'Log in/Register')]"
        self.clickForgotPassword = "//a[contains(text(),'Forgot Password?!')]"
        self.formEmail = "//p[contains(text(), 'Email')]"
        self.inccorectEmailFormat = "//p[contains(text(), 'Email address format incorrect')]"
        self.form_inputPhone =  "//input[@id='phone']"
        self.form_inputEmail =  "//input[@id='fld_Email']"
        self.form_inputPassword = "//input[@id='fld_Password']"
        self.form_buttonLogin = "//button[@id='btn_Login']"
        self.helloLogin = "//div[contains(text(),'Hello!')]"
        self.popWrongPW = "//h3[contains(text(),'Wrong phone number or password')]"
        self.popLoginUnregistered = "//h3[contains(text(),'This account has not been registered.')]"
        self.popUnregistered = "//h3[contains(text(),'This account has not been registered.')]"
        self.myProfile = "(//div[@class='profiles-container lessThanRow']//div//div//div//img)[1]"
        self.myProfilePin = "(//div[@class='profiles-container lessThanRow']//div//div//div//img)[2]"
        self.skip = "//span[@translate=''][text() = 'Skip']"
        self.continuee = "//span[@translate=''][text() = 'Continue']"
        self.inputPinProfile = "//input[@name='PIN']"
        self.okPin = "//span[text()= 'OK']"
        self.txtResetPin = "//span[text()= 'Reset personal PIN']"
        self.dialogPin = "//md-dialog[@class='common-modal operator-subscription-modal _md md-transition-in']"
        self.containerDialog = "//div[@class='md-dialog-container']"
        self.choosePrefixPhone = "//p[contains(text(),'+62')]"
        self.choosePrefixPhoneMalaysia = "(//div[contains(text(),'+60')])[2]"
        self.inputPrefix = "(//input[@id='searchQuery'])[2]" 
        self.clickListPrefix = "(//*[@id='modal_Login']/div[3]/div[1]/div/div/ul/div[2]/li/div)[1]"