class objectProgramGuide:
    def __init__(self):
        self.navbarProgramGUidance = "//span[text() = 'Program Guide']"
        self.sixDayBefore = "//md-option[@value='6']"
        self.fiveDayBefore = "//md-option[@value='5']"
        self.fourDayBefore = "//md-option[@value='4']"
        self.threeDayBefore = "//md-option[@value='3']"
        self.twoDayBefore = "//md-option[@value='2']"
        self.oneDayBefore = "//md-option[@value='1']"
        self.today = "//md-option[@value='7']"
        self.oneDayAfter = "//md-option[@value='8']"
        self.twoDayAfter = "//md-option[@value='9']"
        self.threeDayAfter = "//md-option[@value='10']"
        self.fourDayAfter = "//md-option[@value='11']"
        self.fiveDayAfter = "//md-option[@value='12']"
        self.sixDayAfter = "//md-option[@value='13']"
        self.opsiDate = "(//div[text() = ' Today '])[1]"
        self.textTomorrow = "//div[text() = ' Tomorrow ']"
        self.textyesterday = "//div[text() = ' Yesterday ']"
        self.opsiChannel = "(//span[@translate='' and text() = 'All Channels'])[1]"
        self.clickLoveFav ="(//div[@class= 'fav-channel fav'])[1]"
        self.clickLove = "(//div[@class= 'fav-channel'])[1]"
        self.epgChannelRCTI = "//div[@id='mirada-epg-channel-00000000000000000001']"
        self.inputSearch = "(//md-autocomplete[@placeholder ='Go to channel'])[1]"
        self.channelGTV = "//div[@class='channel-serviceid' and text()='3']"
        self.dropdownAllchannel = "(//span[@translate='' and text() ='All Channels'])[2]"
        self.ddFavorites = "//span[@translate='' and text() ='Favorites']"
        self.ddNasionalTV = "//div[text() = ' National TV ']"
        self.ddEntertainment = "//div[text() = ' Entertainment ']"
        self.ddNews = "//div[text() = ' News ']"
        self.ddKnowledge = "//div[text() = ' Knowledge ']"
        self.ddKids = "//div[text() = ' Kids ']"
        self.ddMovies = "//div[text() = ' Movies ']"
        self.ddSports = "//div[text() = ' Sports ']"
        self.ddMusic = "//div[text() = ' Music ']"
        self.ddReligion = "//div[text() = ' Religion ']"
        self.ddLifestyle = "//div[text() = ' Lifestyle ']"
        self.cardTransTvCurrent = "//*[@sid='00000000000000000006']/div[@class='mirada-epg-mycolumn mirada-epg-mycolumn-current data-startover']"