class objectTonight:
    def __init__(self):
        self.goTonight = "//li[@name='Tonight']"
        self.navAll = "//md-tab-item[contains(text(),'All')]"
        self.navAllActive = "//md-tab-item[contains(text(),'All') and contains(@class, 'md-tab  md-active')]"
        self.navFilms = "//md-tab-item[contains(text(),'Films')]"
        self.navFilmsActive = "//md-tab-item[contains(text(),'Films') and contains(@class, 'md-tab  md-active')]"
        self.navSports = "//md-tab-item[contains(text(),'Sports')]"
        self.navSportsActive = "//md-tab-item[contains(text(),'Sports') and contains(@class, 'md-tab  md-active')]"
        self.navNews = "//md-tab-item[contains(text(),'News')]"
        self.navNewsActive = "//md-tab-item[contains(text(),'News') and contains(@class, 'md-tab  md-active')]"
        self.navChildren = "//md-tab-item[contains(text(),'Children')]"
        self.navChildrenActive = "//md-tab-item[contains(text(),'Children') and contains(@class, 'md-tab  md-active')]"
        self.navSeries = "//md-tab-item[contains(text(),'Series')]"
        self.navSeriesActive = "//md-tab-item[contains(text(),'Series') and contains(@class, 'md-tab  md-active')]"
        self.navEntertainment = "//md-tab-item[contains(text(),'Entertainment')]"
        self.navEntertainmentActive = "//md-tab-item[contains(text(),'Entertainment') and contains(@class, 'md-tab  md-active')]"
        self.navCulture = "//md-tab-item[contains(text(),'Culture')]"
        self.navCultureActive = "//md-tab-item[contains(text(),'Culture') and contains(@class, 'md-tab  md-active')]"
        self.navMusic = "//md-tab-item[contains(text(),'Music')]"
        self.navMusicActive = "//md-tab-item[contains(text(),'Music') and contains(@class, 'md-tab  md-active')]"
        self.selectFilter = "//md-select[@aria-label='Ordering filter']"
        self.filterProgress = "//md-option[@value='nearesttime]"
        self.filterProgressActive = "//md-option[@value='nearesttime' and @selected='selected']"
        self.filterChannels = "//md-option[@value='channel']"
        self.filterChannelsActive = "//md-option[@value='channel' and @selected='selected']"
        self.filterAlphabet = "//md-option[@value='alpha']"
        self.filterAlphabetActive = "//md-option[@value='alpha' and @selected='selected']"