class objectTransactionHistory:
    def __init__(self):
        self.failedTab = "//*[@id='app']/div/div/div/div/div[1]/div[2]/button[3]"
        self.pendingTab = "//*[@id='app']/div/div/div/div/div[1]/div[2]/button[4]"
        self.successTab = "//*[@id='app']/div/div/div/div/div[1]/div[2]/button[2]"
        self.cardPending = "//*[@id='app']/div/div/div/div/div[2]/div/div/button[1]"
        self.cardFailed = "//*[@id='app']/div/div/div/div/div[2]/div/div/button[1]"
        self.cardSuccess = "//*[@id='app']/div/div/div/div/div[2]/div/div/button[1]"
        self.txtVerifyPending = "//p[contains(text(),'Verifying your payment')]"
        self.txtPaymentFailed = "//*[@id='app']/div/div/div/div[3]/ul/li/p[1]"
        self.txtPaymentSuccess = "//div[contains(text(),'Payment Success')]"
        self.threePoint = "//*[@id='app']/div/div/div/div/div[2]/div/div/button[1]/div[1]/div/div/div[2]/button"
        self.btnBuyAgain = "//button[contains(text(),'Buy Again')]"
        self.btnHelpCenter = "//button[contains(text(),'Help Center')]"
        self.txtGetInTouchWithUs = "//p[contains(text(),'Get in Touch With Us')]"
        self.txtOtherPayment = "//p[contains(text(),'Other Payment')]"
        self.statusSuccess = "//button[2][@class = 'bg-[#0B5653]  border-[#07E3D0] text-white rounded-full border p-1.5']"
        self.statusPending = "//button[4][@class = 'bg-[#0B5653]  border-[#07E3D0] text-white rounded-full border p-1.5']"
        self.statusFailed = "//button[3][@class = 'bg-[#0B5653]  border-[#07E3D0] text-white rounded-full border p-1.5']"