class objectVoucher:
    def __init__(self):
        self.goVoucher = "//span[contains(text(),'Voucher')]"
        self.inputVoucherId = "//input[@id='customerID']"
        self.btnReedem = "//div[contains(text(),'Reedem')]"
        self.txtInvalidCode = "//label[contains(text(),'Invalid code')]"
        self.txtHasBeenReedemed = "//label[contains(text(),'This code has been redeemed')]"
        self.txtVoucherHasExpired = "//label[contains(text(),'Voucher code expired')]"
        self.aHelpCenter = "//a[contains(text(),'Help Center')]"
        self.txtDiscoverWhatNew = "//p[contains(text(),'Get In Touch With Us')]"
        self.aTokopedia = "//label[contains(text(),'Tokopedia')]"
        self.tokpedPageVision = "//img[@alt='Vision+']"
        self.aLazada = "//label[contains(text(),'Lazada')]"
        self.lazadaPageVision = "//h1[contains(text(),'Vision+ Streaming')]"
        self.aBlibi = "//label[contains(text(),'Blibli')]"
        self.blibiPageVision = "//div[contains(text(),'Vision+ Official Store')]"
        self.txtBlibiChatSeller = "//img[@data-src='https://www.static-src.com/frontend/static/img/logo-blibli-blue.0f340eba.svg']"
        self.aCodashop = "//label[contains(text(),'Coda')]"
        self.codashopPageVision = "//h2[contains(text(),'Vision+')]"
        self.txtErrorMessageInputVoucher = "//label[@class='text-[#FF7479] text-[0.8rem]']"
        self.btnSeeMyStatus = "//div[contains(text(),'See my status')]"
        self.txtPaymentSuccess = "//div[contains(text(),'Payment Success')]"
        self.iframeLazada = "//iframe[@id='baxia-dialog-content']"